(cl:defpackage TicTac-srv
  (:use )
  (:export
   "CALCULATEBESTMOVE"
   "<CALCULATEBESTMOVE-REQUEST>"
   "CALCULATEBESTMOVE-REQUEST"
   "<CALCULATEBESTMOVE-RESPONSE>"
   "CALCULATEBESTMOVE-RESPONSE"
  ))

